---
- name: "Create docker volume {{ docker_volume_name }}"
  docker_volume:
    name: "{{ docker_volume_name }}"
  when: docker_volume_name is defined and docker_volume_name is not none

- import_tasks: script.yml
- import_tasks: commandline.yml

- name: Register docker volume backup job
  cron:
    name: "Backup job {{ docker_volume_backup_cron_job_id }}"
    hour: "{{ docker_volume_backup_hour }}"
    minute: "{{ docker_volume_backup_minute | default(59 | random(seed=docker_volume_backup_cron_job_id)) }}"
    job: "{{ docker_volume_script_cmdline }} >> {{ docker_volume_backup_cron_job_logfile }} 2>&1"
    disabled: "{{ docker_volume_backup_cron_job_disabled | default(false) }}"
    state: "{{ docker_volume_backup_cron_job_state | default('present') }}"
  when: docker_volume_for_container is defined and docker_volume_backup_dirs | length > 0
