---
- name: Converge
  hosts: all
  vars_files:
    - vars/converge.yml
  pre_tasks:
    - name: "Create container"
      docker_container:
        command: "{{ container_command }}"
        image: "{{ container_image }}"
        name: "{{ container_name }}"
        state: started
        volumes:
          - "{{ docker_volume_name }}:/{{ docker_volume_backup_dirs[0] }}"

  roles:
    - ansible-role-docker_volume
